# Generated by Django 5.0.6 on 2025-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='password',
            field=models.CharField(default=11111111, max_length=10, unique=True),
        ),
    ]
