# Generated by Django 5.0.6 on 2025-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist_portal', '0002_patientprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
