# Generated by Django 5.1.6 on 2025-03-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
