# Generated by Django 5.0.6 on 2025-04-13 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messaging',
            index=models.Index(fields=['sender', 'recipient'], name='messaging_m_sender__c040a6_idx'),
        ),
        migrations.AddIndex(
            model_name='messaging',
            index=models.Index(fields=['created_at'], name='messaging_m_created_4b11b6_idx'),
        ),
    ]
