# Generated by Django 5.1.7 on 2025-04-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
